
apiVersion: v1
kind: Deployment
metadata:
   annotations:
      name: k8sliveness
      labels:
         env: prod
   spec:
      replicas: 3,
      selector:
         matchlabels:
            env: prod
      strategy:
         type: RollingUpdate
         rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
      template:  
         metadata:  
            labels:  
               env: prod
      containers:
      -  image: twogghub/k8s-workshop:1.3-liveness
         name: k8sliveness
         livenessProbe:
           httpGet:
             path: /healthy
             port: 9090
           initialDelaySeconds: 5
           timeoutSeconds: 1
           periodSeconds: 10
           failureThreshold: 3
         ports:
           - containerPort: 9090
             name: http
             protocol: TCP
