--- 
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: k8sliveness
spec: 
  replicas: 3
  selector: 
    matchlabels: 
      env: prod
  spec: 
    containers: 
      - 
        image: "twogghub/k8s-workshop:1.3-liveness"
        livenessProbe: 
          failureThreshold: 3
          httpGet: 
            path: /healthy
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
        name: k8sliveness
        ports: 
          - 
            containerPort: 9090
  strategy: 
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template: 
    metadata: 
      labels: 
        env: prod
