apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8sliveness
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      env: prod
  template:  
    metadata:  
      labels:  
        env: prod
    spec:
      containers:
        - image: twogghub/k8s-workshop:1.3-liveness
          name: k8sliveness
          livenessProbe:
            httpGet:
              path: /healthy
              port: 9090
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
            failureThreshold: 1
          ports:
          - name: http
            containerPort: 9090
