apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8sprod
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:  
    metadata:  
      labels:  
        env: prod
    spec:
      containers:
        - image: twogghub/k8s-workshop:1.2-yaml
          name: k8sprod
          ports:
          - name: http
            containerPort: 8080
